# Generated by Django 4.0.6 on 2022-09-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiresume', '0011_codingskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('percentage', models.CharField(blank=True, max_length=3, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='digiresume/media/codingskills')),
            ],
        ),
    ]
