# Generated by Django 4.0.6 on 2022-09-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiresume', '0012_frameworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworks',
            name='percentage',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
