# Generated by Django 4.0.6 on 2022-09-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiresume', '0013_alter_frameworks_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworks',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
