# Generated by Django 4.0.6 on 2022-09-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiresume', '0019_rename_links_blogs_links_left_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs_links',
            name='row',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
