# Generated by Django 4.0.6 on 2022-09-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiresume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='first',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
