# Generated by Django 4.0.6 on 2022-09-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiresume', '0002_me_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='pro_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
