# Generated by Django 4.0.6 on 2022-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiresume', '0006_alter_me_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='resume',
            field=models.FileField(null=True, upload_to='digiresume/media/me'),
        ),
    ]
