# Generated by Django 4.0.6 on 2022-09-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiresume', '0016_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
