# Generated by Django 4.0.6 on 2022-09-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiresume', '0017_alter_portfolio_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('statement', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='digiresume/media/testimony')),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
