# Generated by Django 4.0.6 on 2022-09-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiresume', '0018_blogs_links_certificates_testimonials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs_links',
            old_name='links',
            new_name='left_links',
        ),
        migrations.AddField(
            model_name='blogs_links',
            name='right_links',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
